version: '3.7'

services:
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_ROOTPASSWORD=${DATABASE_ROOTPASSWORD}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_DIR=${DATABASE_DIR}
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_ROOTPASSWORD=${DATABASE_ROOTPASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_DIR=${DATABASE_DIR}
    networks:
      - inception
    volumes:
      - volume-mariadb:${DATABASE_DIR}

  wordpress:
    depends_on: 
      - mariadb
    container_name: wordpress
    restart: unless-stopped
    build:
      context: ./requirements/wordpress
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_EMAIL=${DATABASE_EMAIL}
        - WP_USERNAME=${WP_USERNAME}
        - WP_PASSWORD=${WP_PASSWORD}
        - WP_EMAIL=${WP_EMAIL}
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_EMAIL=${DATABASE_EMAIL}
      - WP_USERNAME=${WP_USERNAME}
      - WP_PASSWORD=${WP_PASSWORD}
      - WP_EMAIL=${WP_EMAIL}
    networks:
      - inception
    volumes:
      - volume-wordpress:/var/www/html
    
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    restart: unless-stopped
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - CERT_CRT=${CERT_CRT}
        - CERT_KEY=${CERT_KEY}
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CERT_CRT=${CERT_CRT}
      - CERT_KEY=${CERT_KEY}
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - volume-wordpress:/var/www/html

networks:
  inception:
    driver: bridge

volumes:
  volume-mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/mariadb
  volume-wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/wordpress
